pipeline {
    agent any

    stages {
        stage('Unit Tests Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }

        stage ('Unit Test - Frontend') {
            agent {
                docker {
                    image 'node:20-alpine'
                    reuseNode True
                }
            }
            Steps {
                dir('bugtacker-frontend') {
                    sh '''
                      npm ci
                      npm test
                    '''
                }
            }
        }
    }
}