jenkins pipeline {
     agent any environment { GOPATH = '/go' }
     
     stages { stage('Unit Tests Backend') {
         agent { 
            docker { 
                image 'golang:1.21-alpine' 
                reuseNode true
                 } 
            } 
            steps { 
                dir('bugtracker-backend') {
                     sh 'go test -v ./...' 
                } 
            }
         }
     }
 }

#pipeline {
#    GOPATH 
#    agent any
#
#    stages {
#        stage('Unit Tests Backend') {
#            agent{
#                docker {
#                    image 'snakee/golang-junit:1.21'
#                    reuseNode true
#                }
#            }
#            steps {
#                dir('bugtracker-backend') {
#                    sh 'go test -v ./...'
#                }
#            }
#        }
#    }
#}