pipeline {
    agent any

    stages {
        stage('Unit Tests Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            steps {
                dir('bug-tracker') {
                    sh 'go test -v ./...'
                }
            }
        }
    }
}